### ISSUE TITLE
Top container uniqueness?

### ISSUE THREAD

**Issue by cdibella** [harvard-library/aspace-import-excel#11]
@bobbi-SMR - Since people can load things in iteratively with your plugin, I'm wondering what, if any, checks you do for top container uniqueness. If a top container already exists, what happens?

I ask because it's been called to our attention that starting with the 2.1 version of ASpace (when the old container model code was removed) that EADs can be rejected if the top containers in them are already in the system. If presumably spreadsheets loaded in with your plugin do not get rejected for the same reason, I'm wondering if there's something we can learn from your code for the core. Thanks in advance for any insights!

**Comment by bobbi-SMR** [comment]
@cdibella - As described in the  [documenation](https://github.com/harvard-library/aspace-import-excel/blob/master/user_documentation/USER_DOCUMENTATION.md#contain)  , if a bar code isn't provided, my code looks for a top container already associated with a resource, and, if it doesn't find one, it creates one.  Is there now a uniqueness of top container names across resources?

**Comment by cdibella** [comment]
@lmcglohon – I had asked @bobbi-SMR for insight into how her plugin code deals with the issue of matching existing top containers since we discovered that post 2.1 versions of ASpace were enforcing top container uniqueness based on barcode. I see you put in a pull request into our core code related to this (see https://github.com/archivesspace/archivesspace/pull/990). Might the two of you want to put your heads together on this? (Laney is looking for a code review in any case.)

@bobbi-SMR - I’m not sure if our 2.1+ code was enforcing uniqueness with anything besides barcode, but Laney will. I think what you lay out in your documentation is what we want to replicate in terms of allowing people to add to existing top containers.
