### ISSUE TITLE
Error adding to v2.2.0

### ISSUE THREAD

**Issue by mattbaya01267** [harvard-library/aspace-import-excel#12]
I just tried to install this on the recently released v2.2.0 running on Centos 6.9 and got the following error when I ran scripts/initialize-plugin.sh aspace-import-excel;

`[root@archivesspace-dev archivesspace]# ./scripts/initialize-plugin.sh aspace-import-excel
Fetching: bundler-1.12.5.gem (100%)
NotImplementedError: flock unsupported or native support failed to load; see http://wiki.jruby.org/Native-Libraries
                   flock at org/jruby/RubyFile.java:324
   block in write_binary at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems.rb:871
                    open at org/jruby/RubyIO.java:1139
                    open at org/jruby/RubyKernel.java:306
            write_binary at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems.rb:869
       cache_update_path at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/remote_fetcher.rb:334
                download at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/remote_fetcher.rb:188
                download at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/source.rb:211
                 install at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/resolver/specification.rb:91
        block in install at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/request_set.rb:166
                    each at org/jruby/RubyArray.java:1734
                 install at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/request_set.rb:156
             install_gem at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/commands/install_command.rb:205
   block in install_gems at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/commands/install_command.rb:255
                    each at org/jruby/RubyArray.java:1734
            install_gems at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/commands/install_command.rb:251
                 execute at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/commands/install_command.rb:158
  invoke_with_build_args at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/command.rb:310
            process_args at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/command_manager.rb:169
                     run at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/command_manager.rb:139
                     run at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/gem_runner.rb:55
                  <main> at uri:classloader:/META-INF/jruby.home/bin/jgem:21
                    load at org/jruby/RubyKernel.java:979
                  <main> at uri:classloader:/META-INF/jruby.home/bin/gem:4
Gem::GemNotFoundException: can't find gem bundler (>= 0.a)
  find_spec_for_exe at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems.rb:271
  activate_bin_path at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems.rb:298
             <main> at ../../gems/bin/bundle:22`

When I tried to start archivesspace it fails

i'm assuming this is just not compatible with v2.2.0 yet, but if there's anything other information I can provide here, or anything else else I should check or change please advise. Thanks. -Matt

**Comment by bobbi-SMR** [comment]
Hi, Matt,

We haven't tried it with 2.2.0 yet (which is being installed tomorrow, as it happens).  We'll take a look and get back to you as soon as possible (probably not before Friday, but One Can Hope :-)

Thanks,
Bobbi

**Comment by bobbi-SMR** [comment]
Hi, Matt,

Sorry for the delay; we have a **huge** database, and the person in charge of the upgrade started the indexing before I got a chance to try installing the plugin; I had to wait for the indexing to finish (actually it crashed, but that's not my problem :-)

We had no problem installing the plugin againg 2.2 (we're running on linux, btw).

A colleague here suggests that the problem is not with the plugin, but instead a [problem deep within jRuby](https://github.com/jruby/jruby/issues/3409) ;  I suggest contacting the ArchivesSpace team to ask for help if you can't resolve it yourself.

Sorry to be the bearer of bad news.
