### ISSUE TITLE
Enabling the plugin prevents archivesspace from starting with JRuby error

### ISSUE THREAD

**Issue by askdata01** [harvard-library/aspace-import-excel#24]
Error message from log
    You're seeing this error because you use <code>JRuby::Rack::ErrorApp::ShowStatus</code>.
Configuration:  RHEL 7.4, Apache 2.4.6, php 5.6.33, MySQL 5.6.39, archivesspace 2.3.1, header and style customizations in plugins/local/public

**Comment by bobbi-SMR** [comment]
Hi,

There should have been an actual error (like: `Bundler could not find compatible versions for gem "method_source": ` etc..)  I can't diagnose the problem  immediately with the information provided.  Also: please confirm what version of the plugin you are using.

Thanks!

**Comment by askdata01** [comment]
Bobbi,

Thanks for replying to my issue.  Here is what I am seeing as the actual error:
Could not find gem &#x27;rubyXL (= 3.1.0) java&#x27; in any of the gem sources listed in your Gemfile or available on this machine.
from &#x2F;opt&#x2F;ArchivesSpace&#x2F;archivesspace&#x2F;gems&#x2F;gems&#x2F;bundler-1.12.5&#x2F;lib&#x2F;bundler&#x2F;resolver.rb:356:in `block in verify_gemfile_dependencies_are_found!&#x27;
        from org&#x2F;jruby&#x2F;RubyArray.java:1734:in `each&#x27;
        from &#x2F;opt&#x2F;ArchivesSpace&#x2F;archivesspace&#x2F;gems&#x2F;gems&#x2F;bundler-1.12.5&#x2F;lib&#x2F;bundler&#x2F;resolver.rb:331:in `verify_gemfile_dependencies_are_found!&#x27;
        from &#x2F;opt&#x2F;ArchivesSpace&#x2F;archivesspace&#x2F;gems&#x2F;gems&#x2F;bundler-1.12.5&#x2F;lib&#x2F;bundler&#x2F;resolver.rb:200:in `start&#x27;
        from &#x2F;opt&#x2F;ArchivesSpace&#x2F;archivesspace&#x2F;gems&#x2F;gems&#x2F;bundler-1.12.5&#x2F;lib&#x2F;bundler&#x2F;resolver.rb:184:in `resolve&#x27;
        from &#x2F;opt&#x2F;ArchivesSpace&#x2F;archivesspace&#x2F;gems&#x2F;gems&#x2F;bundler-1.12.5&#x2F;lib&#x2F;bundler&#x2F;definition.rb:200:in `resolve&#x27;
        from &#x2F;opt&#x2F;ArchivesSpace&#x2F;archivesspace&#x2F;gems&#x2F;gems&#x2F;bundler-1.12.5&#x2F;lib&#x2F;bundler&#x2F;definition.rb:140:in `specs&#x27;
        from &#x2F;opt&#x2F;ArchivesSpace&#x2F;archivesspace&#x2F;gems&#x2F;gems&#x2F;bundler-1.12.5&#x2F;lib&#x2F;bundler&#x2F;definition.rb:185:in `specs_for&#x27;
        from &#x2F;opt&#x2F;ArchivesSpace&#x2F;archivesspace&#x2F;gems&#x2F;gems&#x2F;bundler-1.12.5&#x2F;lib&#x2F;bundler&#x2F;definition.rb:174:in `requested_specs&#x27;
        from &#x2F;opt&#x2F;ArchivesSpace&#x2F;archivesspace&#x2F;gems&#x2F;gems&#x2F;bundler-1.12.5&#x2F;lib&#x2F;bundler&#x2F;environment.rb:19:in `requested_specs&#x27;
        from &#x2F;opt&#x2F;ArchivesSpace&#x2F;archivesspace&#x2F;gems&#x2F;gems&#x2F;bundler-1.12.5&#x2F;lib&#x2F;bundler&#x2F;runtime.rb:14:in `setup&#x27;
        from &#x2F;opt&#x2F;ArchivesSpace&#x2F;archivesspace&#x2F;gems&#x2F;gems&#x2F;bundler-1.12.5&#x2F;lib&#x2F;bundler.rb:95:in `setup&#x27;
        from &#x2F;opt&#x2F;ArchivesSpace&#x2F;archivesspace&#x2F;gems&#x2F;gems&#x2F;bundler-1.12.5&#x2F;lib&#x2F;bundler&#x2F;setup.rb:19:in `&lt;main&gt;&#x27;
        from org&#x2F;jruby&#x2F;RubyKernel.java:961:in `require&#x27;
        from uri:classloader:&#x2F;META-INF&#x2F;jruby.home&#x2F;lib&#x2F;ruby&#x2F;stdlib&#x2F;rubygems&#x2F;core_ext&#x2F;kernel_require.rb:133:in `require&#x27;
        from &#x2F;opt&#x2F;ArchivesSpace&#x2F;archivesspace&#x2F;data&#x2F;tmp&#x2F;jetty-0.0.0.0-8089-backend.war-_-any-&#x2F;webapp&#x2F;WEB-INF&#x2F;app&#x2F;main.rb:1:in `&lt;main&gt;&#x27;
        from org&#x2F;jruby&#x2F;RubyKernel.java:961:in `require&#x27;
        from uri:classloader:&#x2F;META-INF&#x2F;jruby.home&#x2F;lib&#x2F;ruby&#x2F;stdlib&#x2F;rubygems&#x2F;core_ext&#x2F;kernel_require.rb:55:in `require&#x27;
        from &#x2F;opt&#x2F;ArchivesSpace&#x2F;archivesspace&#x2F;data&#x2F;tmp&#x2F;jetty-0.0.0.0-8089-backend.war-_-any-&#x2F;webapp&#x2F;WEB-INF&#x2F;app&#x2F;main.rb:1:in `block in (root)&#x27;
        from org&#x2F;jruby&#x2F;RubyBasicObject.java:1687:in `instance_eval&#x27;
        from &#x2F;opt&#x2F;ArchivesSpace&#x2F;archivesspace&#x2F;data&#x2F;tmp&#x2F;jetty-0.0.0.0-8089-backend.war-_-any-&#x2F;webapp&#x2F;WEB-INF&#x2F;config.ru:1:in `(root)&#x27;
        from &#x2F;opt&#x2F;ArchivesSpace&#x2F;archivesspace&#x2F;data&#x2F;tmp&#x2F;jetty-0.0.0.0-8089-backend.war-_-any-&#x2F;webapp&#x2F;WEB-INF&#x2F;config.ru:4:in `&lt;main&gt;&#x27;
        from launcher&#x2F;launcher.rb:92:in `start_server&#x27;
        from launcher&#x2F;launcher.rb:157:in `main&#x27;
        from launcher&#x2F;launcher.rb:261:in `&lt;main&gt;&#x27;

We are running v 2.1.2 of the plugin and Aspace 2.3.1

Hope this helps!
Thanks,
Steve

**Comment by bobbi-SMR** [comment]
Hi, Steve, thanks for getting back to me.

I'm not a complete expert on ArchivesSpace compiling, but it looks like you didn't run the 
the scripts/initialize-plugin script?
    for Linux, that's scripts/initialize-plugin.sh aspace-import-excel
    for Windows, that's scripts/initialize-plugin.bat aspace-import-excel

That should have installed the RubyXL on your server.

Is it possible that you ran the initialize-plugin, but got errors?

**Comment by askdata01** [comment]
No, but it’s very possible I never ran the initialize plugin script.  Senior moments are starting to occur more frequently.
Thanks for your help and pointing me in the right direction.  That solved the problem and all seems to be working.  It always helps to follow the directions. ☺
Steve

**Comment by bobbi-SMR** [comment]
Glad to hear it's working now!  I'll close out the issue.

Cheers,
Bobbi
