### ISSUE TITLE
404 Error accessing "/admin/resources/80/getfile" when clicking on "Load via Spreadsheet" button

### ISSUE THREAD

**Issue by avatar382** [harvard-library/aspace-import-excel#27]
Hello,

On an ArchivesSpace v2.2.2 instance, A 404 error is thrown when trying to populate a resource from spreadsheet.

The error from the log is:
 ActionController::RoutingError (No route matches [POST] "/admin/resources/80/getfile"):

I've verified that the plugin is installed in plugins/, and viewing the resources_updates_controller.rb controller in plugins/aspace-import-excel/frontend/controllers, I can see that the getfile action is defined there, and the relevant routes are defined in plugins/aspace-import-excel/frontend/routes.rb.

I've also verified that the config/config.rb file has 'aspace-import-excel' specified in AppConfig[:plugins], and that the plugin has been initialized with scripts/initialize-plugin.sh.

It looks like the plugin is installed correctly, is there anything else that could be causing the plugin to not load correctly?

Thank you!

**Comment by bobbi-SMR** [comment]
Hi, 
It sounds like you've done everything right!  I'm running this by another pair of eyes to see if there's something I"m missing; I'll get back to you tomorrow.

Just to be sure: which tagged version did you download?

**Comment by bobbi-SMR** [comment]
Hi, I'm back :-)  

We can't figure out anything obvious, but I'm looking at the error message's path, and wondering if the **/admin** piece may be causing the problem.  Is **/admin** the "root" of your version of archivesSpace?  If, in your browser you type in: **_{domain}_/admin/resources/80** , do you get your resource displayed?

**Comment by avatar382** [comment]
Hi! Thank you for your response, and I apologize for the delay in responding back. 

I just upgraded to version 2.1.5, and replicated the issue under that version as well.

/admin *is* at the root of ArchivesSpace, and /admin/resources/80 displays the resource. Should we try to reconfigure our frontend to use a different port instead of /admin?

**Comment by bobbi-SMR** [comment]
Hi, Manny,

I was out all last week, so I'm playing catchup with everything.  I'll try to get back to you by Wednesday.

**Comment by bobbi-SMR** [comment]
Hi, Manny,

Sorry for the delay.  I consulted with my Aspace-savvy co-worker, and he suggested that perhaps you didn't run the plugin initializer script?  He ran into the 404 issue when he forgot to do it for a different plugin.  Otherwise, I got nothing :-(

**Comment by avatar382** [comment]
Thanks, Bobbi -- I did run the init script, but I'll take a close look at it and make sure that whatever it's supposed to do got done.

**Comment by avatar382** [comment]
Hi Bobbi, I found the problem -- it was indeed caused by our local configuration -- we set up a proxy URL so that the frontend was something like http://archivesspaceinstance.com/admin. Changing it back to the default of http://archivesspaceinstance.com:8080 resolved the problem.

Thanks for your help!
