### ISSUE TITLE
Link Subjects Error

### ISSUE THREAD

**Issue by kfherbert** [harvard-library/aspace-import-excel#28]
When I  Load a spreadsheet where I have attached subject ID for existing subject or from a Subject Term I get the error

NOT FOUND: 'injest' not found in list subject_source

No subject is added to the created archival object, which seems to be created but not complete, other information like top container is also omitted. I can create new subject via the spreadsheet with no error.

**Comment by bobbi-SMR** [comment]
Hi,

I'm not seeing the spreadsheet, but do you really have a subject "injest", not "ingest"??

**Comment by kfherbert** [comment]
No it is with a G, that is odd, I just cut and pasted it over.

**Comment by bobbi-SMR** [comment]
Can you attach the spreadsheet?  (And include the row number that was reported out with the error)?

**Comment by kfherbert** [comment]
[Executive_Council_test2.xlsx](https://github.com/harvard-library/aspace-import-excel/files/1868870/Executive_Council_test2.xlsx)

**Comment by bobbi-SMR** [comment]
hi, there,
Color me confused: I'm not seeing either a subject id or subject text in the one-row spreadsheet you sent me.

**Comment by kfherbert** [comment]
[Executive_Council_test2.xlsx](https://github.com/harvard-library/aspace-import-excel/files/1869069/Executive_Council_test2.xlsx)

Sorry, I apparently had over written it when I tested the agent functions. Here is the correct spreadsheet.

**Comment by bobbi-SMR** [comment]
ok, so you're getting errors on the first row (Row 6), correct?  and the value of subject ID 112 is... "ingest"?
I notice you've started your Hierarchical relationship at 2, rather than 1, so you've associated this with an already-created Archival Object?

**Comment by kfherbert** [comment]
The value for 112 should be "Women--Employment--Maine."

Yes I am adding a child to an already existing Archival Object.

**Comment by bobbi-SMR** [comment]
ok, so when you open the subject  "Women--Employment--Maine." in ASpace, what source is shown?
(I'll have to pick this up tomorrow).

**Comment by kfherbert** [comment]
Library of Congress Subject Headings

**Comment by bobbi-SMR** [comment]
Ok, since your subject sources, etc. are different from mine, I wonder if you would try again, and, this time, copy the results to the clipboard, and paste them into a file, attaching them here.  Because I can't duplicate your error, and I'm not seeing how/where it's being generated in my code.  Also: which version are you using?

Thanks,

**Comment by kfherbert** [comment]
We are in AS version 2.0 so I believe we are using v1.7.8 of the plugin. 
I uploaded the exact spreadsheet I sent to you. There error as copied to clipboard from the message

  Row	Status	Title	URI	Info
  Row 6  
     No Archival Object created
         				ERROR: NOT FOUND: 'ingest' not found in list subject_source

  Row 7  
     No Archival Object created
         				Top Container [Box 1] created: /repositories/3/top_containers/871

      				ERROR: NOT FOUND: 'ingest' not found in list subject_source



Thanks!

**Comment by bobbi-SMR** [comment]
Aha!  "ingest" not "injest"! (Sorry, I got confused by your initial reply wrt the spelling)

Apparently, you don't have the "ingest" value (which has the translation of "Unspecified ingested source"  ) in your Subject Source Controlled Value list.

 I'm under the impression that this value comes standard with ASpace, so someone either deleted it or something else went wrong.  

"ingest" is the default value for subject_source in my plugin; you can override it in the **Subject(n) Source** field in the spreadsheet.  Or (assuming you have "admin" privileges), you can add "ingest" back into the subject_source Controlled List.

hth

**Comment by kfherbert** [comment]
That worked. Thank you very much.

**Comment by bobbi-SMR** [comment]
Great!  I'm closing this out.

Cheers,
