### ISSUE TITLE
AO import Digital Object thumbnail (second file version) not loading

### ISSUE THREAD

**Issue by ebrplSpecialCollections** [harvard-library/aspace-import-excel#37]
I've been trying to load archival objects with associated digital objects using the template provided but for some reason the thumbnail link will not import.  No errors appear when uploading.  I didn't realize it was an issue until I had gone back to check the end product.  I am attaching 
[brfa001_DAO_pt5.xlsx](https://github.com/harvard-library/aspace-import-excel/files/2212249/brfa001_DAO_pt5.xlsx)
one of the spreadsheets I used for your inspection.  

Much appreciated! This is a great tool!

**Comment by bobbi-SMR** [comment]
Hi,

I’ll be taking a look at this on Monday.

I just want to check: which version of this tool are you using?

Cheers,
Bobbi

**Comment by bobbi-SMR** [comment]
Hi.  Some extraneous text crept into the ArchivesSpace field code for thumbnails, so my code wasn't picking it up.  I'll be releasing a new version of the template later today, but thought I'd rush this to you in the meantime.

Thanks for your patience!


[aspace_import_excel_template.xlsx](https://github.com/harvard-library/aspace-import-excel/files/2219833/aspace_import_excel_template.xlsx)

**Comment by ebrplSpecialCollections** [comment]
Hey Bobbi,

That did the trick! Thanks for your speedy work! I also was using the wrong version of the plugin so I fixed that.

Thanks again!

Emily

On Jul 23, 2018, at 10:04 AM, Bobbi Fox at Harvard LTS <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi. Some extraneous text crept into the ArchivesSpace field code for thumbnails, so my code wasn't picking it up. I'll be releasing a new version of the template later today, but thought I'd rush this to you in the meantime.

Thanks for your patience!

aspace_import_excel_template.xlsx<https://github.com/harvard-library/aspace-import-excel/files/2219833/aspace_import_excel_template.xlsx>
