### ISSUE TITLE
 Problem with ASpace Service starting after Plugin install

### ISSUE THREAD

**Issue by dcarlsonatsys** [harvard-library/aspace-import-excel#38]
Good Afternoon,  I recently installed the aspace-import-excel plugin to my Test server.  Its running AS 2.4.1.  When attempting to restart the ASpace service to test the plugin I receive the below output in the achivessapce.out log:

You're seeing this error because you use <code>JRuby::Rack::ErrorApp::ShowStatus</code>.
    </p>
  </div>
</body>
</html>
).  Retrying...
Jul 25, 2018 3:44:09 PM org.eclipse.jetty.server.handler.ContextHandler$Context log
INFO: DEBUG: due a previous initialization failure application instance can not be returned
Jul 25, 2018 3:44:09 PM org.eclipse.jetty.server.handler.ContextHandler$Context log
INFO: DEBUG: resetting rack response due exception
E, [2018-07-25T15:44:09.659499 #15169] ERROR -- : Thread-2002: Connection to backend failed (<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <title>Internal Server Error at &#x2F;config&#x2F;enumerations</title>
  <meta name="robots" content="NONE,NOARCHIVE" />
  <style type="text/css">
    html * { padding:0; margin:0; }
    body * { padding:10px 20px; }
    body * * { padding:0; }
    body { font:small sans-serif; background:#eee; }
    body>div { border-bottom:1px solid #ddd; }
    h1 { font-weight:normal; margin-bottom:.4em; }
    h1 span { font-size:60%; color:#666; font-weight:normal; }
    table { border:none; border-collapse: collapse; width:100%; }
    td, th { vertical-align:top; padding:2px 3px; }
    th { width:12em; text-align:right; color:#666; padding-right:.5em; }
    #info { background:#f6f6f6; }
    #info ol { margin: 0.5em 4em; }
    #info ol li { font-family: monospace; }
    #summary { background: #ffc; }
    #explanation { background:#eee; border-bottom: 0px none; }
  </style>
</head>
<body>
  <div id="summary">
    <h1>Internal Server Error <span>(500)</span></h1>
    <table class="meta">
      <tr>
        <th>Request Method:</th>
        <td>GET</td>
      </tr>
      <tr>
        <th>Request URL:</th>
        <td>http:&#x2F;&#x2F;localhost:8089&#x2F;config&#x2F;enumerations</td>
      </tr>
    </table>
  </div>
  <div id="info">
    <p>
[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: pry (&gt;= 0) and pry (~&gt; 0.11.3). Bundler cannot continue.

#  from &#x2F;archivesspace&#x2F;data&#x2F;tmp&#x2F;jetty-0.0.0.0-8089-backend.war-_-any-&#x2F;webapp&#x2F;WEB-INF&#x2F;Gemfile:58
#  -------------------------------------------
#  require &#x27;asutils&#x27;
&gt;  ASUtils.load_plugin_gems(self)
#  -------------------------------------------

        from &#x2F;archivesspace&#x2F;gems&#x2F;gems&#x2F;bundler-1.16.1&#x2F;lib&#x2F;bundler&#x2F;dsl.rb:110:in `gem&#x27;
        from (eval):6:in `&lt;eval&gt;&#x27;
        from org&#x2F;jruby&#x2F;RubyBasicObject.java:1693:in `instance_eval&#x27;
        from uri:classloader:&#x2F;asutils.rb:245:in `block in load_plugin_gems&#x27;
        from org&#x2F;jruby&#x2F;RubyArray.java:1734:in `each&#x27;
        from uri:classloader:&#x2F;asutils.rb:241:in `load_plugin_gems&#x27;
        from &#x2F;archivesspace&#x2F;data&#x2F;tmp&#x2F;jetty-0.0.0.0-8089-backend.war-_-any-&#x2F;webapp&#x2F;WEB-INF&#x2F;Gemfile:58:in `&lt;eval&gt;&#x27;
        from org&#x2F;jruby&#x2F;RubyBasicObject.java:1705:in `instance_eval&#x27;
        from &#x2F;archivesspace&#x2F;gems&#x2F;gems&#x2F;bundler-1.16.1&#x2F;lib&#x2F;bundler&#x2F;dsl.rb:47:in `eval_gemfile&#x27;
        from &#x2F;archivesspace&#x2F;gems&#x2F;gems&#x2F;bundler-1.16.1&#x2F;lib&#x2F;bundler&#x2F;dsl.rb:12:in `evaluate&#x27;
        from &#x2F;archivesspace&#x2F;gems&#x2F;gems&#x2F;bundler-1.16.1&#x2F;lib&#x2F;bundler&#x2F;definition.rb:35:in `build&#x27;
        from &#x2F;archivesspace&#x2F;gems&#x2F;gems&#x2F;bundler-1.16.1&#x2F;lib&#x2F;bundler.rb:135:in `definition&#x27;
        from &#x2F;archivesspace&#x2F;gems&#x2F;gems&#x2F;bundler-1.16.1&#x2F;lib&#x2F;bundler.rb:101:in `setup&#x27;
        from &#x2F;archivesspace&#x2F;gems&#x2F;gems&#x2F;bundler-1.16.1&#x2F;lib&#x2F;bundler&#x2F;setup.rb:20:in `&lt;main&gt;&#x27;
        from org&#x2F;jruby&#x2F;RubyKernel.java:961:in `require&#x27;
        from uri:classloader:&#x2F;META-INF&#x2F;jruby.home&#x2F;lib&#x2F;ruby&#x2F;stdlib&#x2F;rubygems&#x2F;core_ext&#x2F;kernel_require.rb:133:in `require&#x27;
        from &#x2F;archivesspace&#x2F;data&#x2F;tmp&#x2F;jetty-0.0.0.0-8089-backend.war-_-any-&#x2F;webapp&#x2F;WEB-INF&#x2F;app&#x2F;main.rb:1:in `&lt;main&gt;&#x27;
        from org&#x2F;jruby&#x2F;RubyKernel.java:961:in `require&#x27;
        from uri:classloader:&#x2F;META-INF&#x2F;jruby.home&#x2F;lib&#x2F;ruby&#x2F;stdlib&#x2F;rubygems&#x2F;core_ext&#x2F;kernel_require.rb:55:in `require&#x27;
        from &#x2F;archivesspace&#x2F;data&#x2F;tmp&#x2F;jetty-0.0.0.0-8089-backend.war-_-any-&#x2F;webapp&#x2F;WEB-INF&#x2F;app&#x2F;main.rb:1:in `block in (root)&#x27;
        from org&#x2F;jruby&#x2F;RubyBasicObject.java:1687:in `instance_eval&#x27;
        from &#x2F;archivesspace&#x2F;data&#x2F;tmp&#x2F;jetty-0.0.0.0-8089-backend.war-_-any-&#x2F;webapp&#x2F;WEB-INF&#x2F;config.ru:1:in `(root)&#x27;
        from &#x2F;archivesspace&#x2F;data&#x2F;tmp&#x2F;jetty-0.0.0.0-8089-backend.war-_-any-&#x2F;webapp&#x2F;WEB-INF&#x2F;config.ru:4:in `&lt;main&gt;&#x27;
        from launcher&#x2F;launcher.rb:92:in `start_server&#x27;
        from launcher&#x2F;launcher.rb:157:in `main&#x27;
        from launcher&#x2F;launcher.rb:261:in `&lt;main&gt;&#x27;
</p>
  </div>

That continues in an endless loop an the pages never come up.  Assistance is greatly appreciated.

Regards,

**Comment by bobbi-SMR** [comment]
Hi,

What version of the plugin are you using?  It looks like you’re using an older version that includes pry in its Gemfile, which is no longer the case.  Please download Version v2.1.10, (https://github.com/harvard-library/aspace-import-excel/releases/tag/v2.1.10 )  [or any version v2.1.7 & higher) and try again.

Please let me know what happens.

Thanks,
Bobbi

**Comment by dcarlsonatsys** [comment]
EDIT:
Thank you Bobbi.  I will do that.

One other question…  Are there any special permissions that I need to run the scripts/initialize-plugin.bat aspace-import-excel With?

Does the Plugin folder need to be renamed from aspace-import-excel-master to just aspace-import-excel?  Since aspace-import-excel is being listed for the config.rb.

Regards,

David Carlson
System Administrator
Atlas Systems - Library excellence through efficiency
phone: (757) 467-7872 x238     fax: (757) 467-7875
dcarlson@atlas-sys.com<mailto:dcarlson@atlas-sys.com>
https://www.atlas-sys.com/

Thanks to our customers and partners for making FY2017/2018 an exciting one for us, with new licensees and new service offerings (have you heard about AtlasBI<https://www.atlas-sys.com/atlasbi/>?). We’re closing the books on this fiscal year and eagerly looking forward to what FY2018/2019 will bring. Read our end-of-year summary here<https://www.atlas-sys.com/news/>.

Notice:  This e-mail message, including any attachments, is intended only for the named recipient(s) above and may contain confidential information.  If you have received this message in error, or are not the named recipient(s), please immediately notify the sender and delete this e-mail message from your computer without making any copies or distributing it to any other person.  Thank you.

**Comment by bobbi-SMR** [comment]
Hi, David,

I’m not aware of any special permissions; I assume if you can start/stop ArchivesSpace, you have the permissions you need.  Note that we run under linux, not Windows, so your mileage may vary.

Cheers,
Bobbi

**Comment by dcarlsonatsys** [comment]
Yep Linux Debian Jessie to be exact.  Thank you.  I will give it another go.  Much appreciated.

**Comment by dcarlsonatsys** [comment]
Ok no joy.  Getting this:

**Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.**

**[!] There was an error parsing `Gemfile`: No such file or directory - /archivesspace/plugins/aspace-import-excel/Gemfile. Bundler cannot continue.**

I then tried running it as myself:
**root@asdgc:/archivesspace# su dcarlson scripts/initialize-plugin.sh aspace-import-excel
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the gems directory.**

**[!] There was an error parsing `Gemfile`: No such file or directory - /archivesspace/plugins/aspace-import-excel/Gemfile. Bundler cannot continue**.

**Comment by bobbi-SMR** [comment]
[!] There was an error parsing Gemfile: **No such file or directory - /archivesspace/plugins/aspace-import-excel/Gemfile**. Bundler cannot continue.

This implies that the Gemfile isn't there; when you do an `ls ~/archivesspace/plugins` , do you see **aspace-import-excel** ?

Depending on how you downloaded/unzipped the plugin, it may have ended up with the plugin being named **aspace-import-excel-2.1.10**, which you then rename to **aspace-import-excel**

**Comment by dcarlsonatsys** [comment]
Yes the file folder is there and shows aspace-import-excel as being in the directory of /archivesspace/plugins

It was originally named **aspace-import-excel-master** as I downloaded it via chrome and then copied it via WinSCP to the server.

I then I unzipped it and renamed it to just **aspace-import-excel** since that's what it calls for in the documentation for the config.rb

**Comment by bobbi-SMR** [comment]
so when you `ls -l ~/archivesspace/plugins/aspace-import-exel/Gemfile`, what do you see?  The bundler is reporting that it can't find that file, which is why I asked you about the directory.

**Comment by dcarlsonatsys** [comment]
drwxr-xr-x 5 root root 4096 Jul 26 11:18 aspace-import-excel-master
drwxr-xr-x 9 root root 4096 Jul 26 11:19 gems

I looked for the gemfile and found it in:
/archivesspace/plugins/aspace-import-excel/aspace-import-excel-master

But it does not appear to have a Gemfile directly under /archivesspace/plugins/aspace-import-excel

**Comment by bobbi-SMR** [comment]
OK:

The zip file from aspace-import-excel-master.zip should have been placed in
`~/archivesspace/plugins`  . If there already was a `~/archivesspace/plugins/aspace-import-excel` directory present, it should have been either deleted (`rm -R ~/archivesspace/plugins/aspace-import-excel` ) or renamed (`mv ~/archivesspace/plugins/aspace-import-excel ~/archivesspace/plugins/aspace-import-excel-previous`). Then the following should have been done:

`$ cd ~/archivesspace/plugins

 $ unzip aspace-import-excel-master.zip

 $ ls -l aspace-import-excel-master # you should see a lot of files

 $ mv aspace-import-excel-master aspace-import-excel

 $ cd ~/archivesspace

 $ scripts/initialize-plugin.sh aspace-import-excel
`
This should find the Gemfile, and the bundler should run smoothly.

**Comment by dcarlsonatsys** [comment]
Eureka.  Not sure how the GemFile was getting smoked.  But I got it working.  Mucho Appreciado!

**Comment by bobbi-SMR** [comment]
Yay!  Closing this out...
