### ISSUE TITLE
Processing stopped at row 6 [Error(s) parsing Excel File No processible data rows found!]

### ISSUE THREAD

**Issue by Blake-** [harvard-library/aspace-import-excel#40]
I just tried the latest version with the latest template and I'm getting this error. I do have an EADID in that field. Am I doing something wrong or is there a bug here?

`Processing stopped at row 6 [Error(s) parsing Excel File No processible data rows found!]
Row 6
Row 6 will not be processed due to errors: This form's Resource is missing an EAD ID
No Archival Object created
`

**Comment by bobbi-SMR** [comment]
Hi, Blake,

Would you send me the spreadsheet (if it's very long, just send the first several rows), or attach it here?

**Comment by Blake-** [comment]
Hi Bobbi
I tried two, one had a BUNCH of real things in it, so then I downloaded an empty one from GitHub and just added a single row with made up things in it, and got the same error.

**Comment by bobbi-SMR** [comment]
And the spreadsheet is where?

**Comment by Blake-** [comment]
[aspace_import_excel_template.xlsx](https://github.com/harvard-library/aspace-import-excel/files/2283776/aspace_import_excel_template.xlsx)

**Comment by bobbi-SMR** [comment]
I'll take a look  this afternoon; I'm thinking that perhaps Excel is reporting that ID as numeric, and that's why it's failing, but I'll know more once I try running it.

**Comment by bobbi-SMR** [comment]
Hi, Blake,

What version of Excel are you using?  Both when I opened up the spreadsheet you attached (to change the extent type; we don't have "cds" as a type) and saved or just downloaded it directly (see result below), I did *not* get the `This form's Resource is missing an EAD ID`
message.
  `
Row	Status	Title	URI	Ref ID	Info
  Row 6       	Archival Object created: 	'Blake Caver, 1969-04-17T00:00:00+00:00'	/repositories/2/archival_objects/2579365	93939c00002
      					ERROR: Unable to validate extent: NOT FOUND: 'cds' not found in list extent_extent_type
`
Given that I can't reproduce the problem, but wondering if you're using a version of Excel that I'm not (I'm using Office 2013, I think), Would you try this:

1. select column C
2. right-click on Format cells...
3. select Text in the category list
4. save and try again.

I'm sorry it's so frustrating!

**Comment by Blake-** [comment]
Still failing on me, still using the same thing, I'm on Libre Office though. I tried a few different formats, still fails. I'm not quite sure what's going on, there's nothing in the logs either. Using 2.4.1

**Comment by bobbi-SMR** [comment]
Hi, Blake,

I apologize for not having paid enough attention to the exact wording of the error message (there are two that are alike enough that not paying attention is a problem :-(

The error being reported means that the *RESOURCE* you're trying to upload the spreadsheet to doesn't seem to have an ead_id.  I know you said that there is one, so I'm a little flummoxed.  (We have a plugin installed that won't allow us to create a Resource without an ead_id, so I can't really replicate).

When you're in the Resource, can you Export an EAD file? if so, would you kindly send it to me/attach it?

Thanks,

**Comment by mhellar** [comment]
Hi I'm getting similar errors, I believe I have all required fields, bobbi-SMR  can I send you a sample of what I'm trying to upload. Also is there a log on the server I can look at to see me detail on the error? Thanks!

![screen shot 2018-10-22 at 1 42 03 pm](https://user-images.githubusercontent.com/161497/47318297-900e4b00-d600-11e8-9100-c01aa9f334bc.png)

**Comment by bobbi-SMR** [comment]
Hi,

You *should* have gotten a popup with a report of each failed line.  Feel free to send me the EAD and sample spreadsheet to bobbi_foxATharvard.edu . Also: what version of Aspace are you using?

**Comment by bobbi-SMR** [comment]
Oh, and the frontend log file (assuming you split your logs) might have some error reports, as well.
