### ISSUE TITLE
Ref ID not found error

### ISSUE THREAD

**Issue by amberjewel** [harvard-library/aspace-import-excel#44]
I keep getting the error that the Ref IDs can't be found when I try to import using the Digital Object import spreadsheet. This is weird, because I have verified that the Ref IDs that I have in the spreadsheet match the Ref IDs on the Archival Objects that I'm trying to attach to, and I have no trailing white space before or after the Ref IDs in the spreadsheet. Any ideas why I'd be getting this error? Please see attached for screenshot of error.
![screen shot 2018-10-19 at 11 25 57 am](https://user-images.githubusercontent.com/14101328/47237027-b5961d00-d392-11e8-8e45-06b6507c6e27.png)

**Comment by bobbi-SMR** [comment]
I have no idea why this is happening!  If you wouldn't mind exporting an EAD and sending it and your spreadsheet, I can try to figure it out.  Send it to bobbi_fox AT harvard.edu, rather than attaching it here in GitHub.

**Comment by pobocks** [comment]
@amberjewel I don't know if you're still having this problem, but that email isn't currently working.  You can send it to me at dave_mayo AT harvard.edu, or @bobbi-SMR can send you her current email out of band.

**Comment by pobocks** [comment]
Closed because Bobbi informed me out of band that this was handled prior.
