### ISSUE TITLE
assertion failed  errors

### ISSUE THREAD

**Issue by bobbi-SMR** [harvard-library/aspace-import-excel#5]
In AS v2.*, got ASSERTION FAILED errors when trying to load spreadsheet
Example:
`ERROR: Unknown response: {"error":"ASSERTION FAILED: {:id=>71329, :repo_id=>4, :lock_version=>0, :json_schema_version=>1, :barcode=>nil, `

[assertion_failed_error.xlsx](https://github.com/harvard-library/aspace-import-excel/files/1075807/assertion_failed_error.xlsx)

Initial grepping suggests that maybe there are IDs being used for agents or subjects which aren't associated with the given repository...

**Comment by bobbi-SMR** [comment]
It looks like the problem is instead in identifying, and using, top containers.

**Comment by pobocks** [comment]
Test
