### ISSUE TITLE
Search/match for agents is too loose

### ISSUE THREAD

**Issue by tufts-digital-collections-archives** [harvard-library/aspace-import-excel#51]
I attempted to import an object with an agent that exists but it errored out as : [More than one match found in the database]. There was an exact match, and there was also a loose match further disambiguated by date. So say I tried to import with Smith, Bill, and our database has both Smith, Bill, and Smith, Bill, 1919-1962, with dates added to further distinguish him from the first guy (as used to be the cataloging standard). It seems to me it would be better to link to the exact match and ignore the inexact match rather than failing to link the agent.

In another instance, there was no exact match, and I would have expected a corporate agent to be created, but it wasn't, because of loose matchiness. For example, let's say I entered The Boston School as a corporate agent; there is no agent with that name, but the words "Boston" and "School" are in a lot of corporate names, so I again got a : [More than one match found in the database] error. Was this discussed during initial development? Was this a purposeful decision?

**Comment by bobbi-SMR** [comment]
We're working on this; hopefully the fix will be available next week
