### ISSUE TITLE
Importing Language to Archival Object Basic Info Rather than Language Notes

### ISSUE THREAD

**Issue by VLSolek** [harvard-library/aspace-import-excel#52]
Does anyone have a tweak to the code that would put an imported language into the Archival Object Basic Info Rather than Language Notes?  I would like to specify language at the item level at the top of the record rather than having it buried in the notes.  Anyone? Help?  Thanks! VivianLea Solek, Archivist, Knights of Columbus Supreme Council Archives.

**Comment by bobbi-SMR** [comment]
Hi, Vivian,
I'm sorry this got so lost in my mail.  By now, if you're using aspace 2.7, I'm hopeful that you are using the latest release at https://github.com/harvard-library/aspace-import-excel/releases/latest, which includes moving the language note up.

**Comment by VLSolek** [comment]
Good morning Bobbi,

Good to hear from you.  We actually are in v2.6 and I’m trying to get stable systems to start importing data.  I’m SO ready for that to happen.  Language is not a huge issue for me – most of my records are in English, so I guess I will get that “fix” next year, when we do our first upgrade.

Many thanks for reaching out and have a great day.

Best,
VivianLea

VivianLea Solek
Archivist
Knights of Columbus Supreme Council Archives

Knights of Columbus Museum
1 State Street
New Haven, CT 06511-6702
Phone 203 752-4578
Fax 203 865-0351
