### ISSUE TITLE
Duplicate Entries after Import and long import time

### ISSUE THREAD

**Issue by bseeger** [harvard-library/aspace-import-excel#57]
Hello, 

We are running Archivesspace 2.5.2 with this plugin (v 2.1.20) installed.  We recently tried importing with a spreadsheet with 4,415 lines, and while it worked well initially, it seemed like it stopped functioning correctly and started to import a number of records a second time. Almost like multiple import processes were running.   I thought it might just need more time to run, but after almost 24 hours it was clear things weren't right. A parent record that should have had about 2,971 items had around 4,000 before I restarted Archivesspace. 

Is there a recommend max limit for the number of rows in the spreadsheet?  What could cause this scenario to happen?

In case it's helpful -- I would occasionally see  "VALIDATION ERROR ON SECOND SAVE"  error in the log (
https://github.com/harvard-library/aspace-import-excel/blob/master/frontend/controllers/resources_updates_controller.rb#L533) though I'm not sure what to do about it or what it means for the record.  (and I lost the log file as I didn't realize that archives space would truncate it upon restart)

Not sure why this happened - any thoughts?

**Comment by bobbi-SMR** [comment]
Hi,

I've never seen the behavior (seeming to import records a second time) before!  If you can upload the spreadsheet (or email it to me at bobbi-smr{AT}bobbifox.net ), I can try to duplicate the problem.  Are you on a Linux or Windows system  (just to be thorough)?

**Comment by bseeger** [comment]
Hi Bobbi, I'll email you the spread sheet.  Thanks, in advance, for looking at it.
It's running on a CentOS 7 server.

**Comment by bobbi-SMR** [comment]
Having had @bseeger 's problem spreadsheet run through without errors, we're unable to duplicate the reported problems.  We do suggest perhaps making spreadsheets smaller, perhaps by having a separate spreadsheet for one or two Series at a time.
