### ISSUE TITLE
Series of error upon import

### ISSUE THREAD

**Issue by bennetse** [harvard-library/aspace-import-excel#58]
Hi, when I try to import the sheet it pops up a dialog box "ERROR: error; Error detected," and then another: "Processing stopped at row 200 [Error(s) parsing Excel File No processible data rows found!]" Each row that I've tried to import shows an error message like this "Row 6 will not be processed due to errors: This form's Resource is missing an EAD ID."

I've followed the suggestion to make sure that the EAD ID is formatted at text and also tried formatting all the rows differently or not at all. Any suggestions?

**Comment by kschlottmann** [comment]
The AS resource record needs to have the identifier in the EAD ID field,
which is found in the Finding Aid Data section.

**Comment by bobbi-SMR** [comment]
Thanks, @kschlottmann for answering the question more quickly than I got to it! 💯 

Also, make sure that the EAD ID on the spreadsheet matches exactly the entry in Finding Aid EAD ID (e.g.: if you have MAD003 in the Finding Aid EAD ID field, don't use mad003 in your spreadsheet).

**Comment by bennetse** [comment]
Alas it does match exactly, to this human eye anyway @kschlottmann @bobbi-SMR There isn't anything else it could be?

**Comment by bobbi-SMR** [comment]
hmm.  I've never seen this problem before where the EADID in the Finding Aid and the EADID in the spreadsheet match to the eye, but don't match, computationally.  Can you upload your spreadsheet, or send it to me (bobbi-SMR AT bobbifox.net)?  And also download the EAD of your resource, then upload/send so I can take a look?

**Comment by bennetse** [comment]
Good news @bobbi-SMR , operator error - turns out that I had the collection id under the Basic Information section but not in the Finding Aid Data section. If anyone else encounters this error, check under FAD! Thanks for everyone's help!

**Comment by bobbi-SMR** [comment]
I love it when users solve their own problems! 😄

**Comment by bennetse** [comment]
Thanks for asking for the EAD, it prompted me to look at it before I sent it and the issue was much more obvious there!
