### ISSUE TITLE
xlink namespace in extref causes scopecontent note import to fail

### ISSUE THREAD

**Issue by kschlottmann** [harvard-library/aspace-import-excel#59]
When uploading mixed content in a scopecontent notes that includes an extref with xlink namespaces, the importer skips the note and throws an error. For example:

`This note includes a namespaced-link here: <extref xlink:type="simple" xlink:href="http://www.example.com">ExampleLink</extref>`

We would like to be able to upload notes with properly-namespaced extrefs.

**Comment by bobbi-SMR** [comment]
I'm sorry it's taken so long to get back to you.

Would you be willing to email me a small spreadsheet with this problem, so that I can examine it more closely?  You can send it to bobbi AT bobbifox.net, or, better, attach it to a reply to this comment.

I will be "off the air" until Wednesday, but will look at it then.  Which version of ArchivesSpace are you running?

**Comment by kschlottmann** [comment]
Thanks Bobbi. Attached is an example. The <extref> in the scopeContent note in row 8 has the xlink prefix. The <extref>s in the scopeContent notes in row 9 and following do not.  

No hurry; we have a workaround (https://github.com/cul/rbml-archivesspace/blob/master/APIFunctions/replace_extrefs.py), but being able to namespace the tags would be a nice-to-have.

[Ephemera collection container list series 4.xlsx](https://github.com/harvard-library/aspace-import-excel/files/3724615/Ephemera.collection.container.list.series.4.xlsx)

**Comment by pobocks** [comment]
I have a theory of how to fix this - I think adding xlink namespace to the wrapper element you use when handling fields with tags would fix it maybe! PR incoming!

**Comment by pobocks** [comment]
I am at DLF right now, @bobbi-SMR or @kschlottmann, if y'all can test this I'd appreciate it, if not, I can do it maybe in a few nights or when I get back.

**Comment by pobocks** [comment]
This is fixed as of v2.1.21, just now released!
