### ISSUE TITLE
Unwanted conversion to date in child indicator column

### ISSUE THREAD

**Issue by bobbi-SMR** [harvard-library/aspace-import-excel#6]
(From A.H:)

Hi Bobbi, 

Attached is the spreadsheet. Column AB “Child Indicator” is the column in question. I wanted to put that this was volumes 1-2, thus input “1-2” in the column. It then converted it to 2-Jan. 
[Pulp Fiction template_child_indicator.xlsx](https://github.com/harvard-library/aspace-import-excel/files/1142589/Pulp.Fiction.template_child_indicator.xlsx)

**Comment by bobbi-SMR** [comment]
The problem is in the Excel Spreadsheet, rather than the code parsing the column.
Referred to @rwendler

**Comment by rwendler** [comment]
I can easily change all the indicator_[n] columns from format "General", where Excel tries to recognize dates and convert them, to format "Text", where it leaves what you type alone. I suspect it would desirable (or at least not harmful) for most if not all columns that do not have controlled lists of values to be formatted as Text. Bobbi, does that seem right to you? If there is any question, I'd prefer that the ASWG specify column formatting and I can make it so. Meanwhile, here's a revised spreadsheet with Text formatting applied to columns for indicator_1, indicator_2, and indicator_3, which are columns Z, AC, and AE in this file.
[aspace_import_excel_template-rev_2017-07-13.xlsx](https://github.com/harvard-library/aspace-import-excel/files/1146390/aspace_import_excel_template-rev_2017-07-13.xlsx)

**Comment by bobbi-SMR** [comment]
The reporting user is satisfied with the change; the template file has been updated
