### ISSUE TITLE
Language of materials note not importing into resource record

### ISSUE THREAD

**Issue by caromeneses** [harvard-library/aspace-import-excel#63]
Hi, we tried importing archival records with language of materials notes and got the following error message: "undefined method `[]' for nil:NilClass" and no archival object was created as result. I'm wondering if this has anything to do with our recent upgrade to 2.7.0, which has the new Language Sub-record. Any feedback would be appreciated. Thank you! - Carolina Meneses

**Comment by juskaise** [comment]
Hi, us at IU are also experiencing this issue with the extended spreadsheet version of the template. Any value placed in the Language of Materials note causes this. The error we get:

```
Processing stopped at row 6 [Error(s) parsing Excel File No processible data rows found!]
Row 6
undefined method `[]' for nil:NilClass
No Archival Object created
```

This stops any creation of the archival object and removes several required-field data from the resource record (although refreshing the page restores them). Thanks for any feedback! - Justina Kaiser

**Comment by bobbi-SMR** [comment]
Hi,
Which version of ArchivesSpace are you on?  If you're on v2.7, you should be using the newest update, https://github.com/harvard-library/aspace-import-excel/releases/tag/v3.0.4 . If you are *not* on v2.7, which version of the plugin are you using?  I may need to look at your spreadsheet.

**Comment by juskaise** [comment]
We're using v2.7; I'll check with our assistants to see which version of the plugin we have and to change it if we grabbed an older update. Thanks for the suggestion!

**Comment by acrande** [comment]
IU is actually using the Tufts fork, which hasn't synched upstream yet...

**Comment by bobbi-SMR** [comment]
The Tufts fork has been incorporated back into the main source here; the fix to the Language of Materials issue is in the designated release ( https://github.com/harvard-library/aspace-import-excel/releases/tag/v3.0.4 ).  The Tufts fork will *not* be further updated.  IU can continue to use the spreadsheet they are using against this new release.

**Comment by acrande** [comment]
Thanks for the update and help. We'll use this source, then.
